# Generated by Django 3.1.7 on 2021-03-10 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations_api', '0001_initial'),
        ('companies_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='locations_api.location'),
        ),
    ]
