# Generated by Django 3.1.7 on 2021-03-10 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies_api', '0002_company_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='home',
            new_name='headquarters',
        ),
    ]
