# Generated by Django 3.1.7 on 2021-03-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_api', '0002_contact_home'),
        ('companies_api', '0003_auto_20210310_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='employees',
            field=models.ManyToManyField(to='contacts_api.Contact'),
        ),
    ]
